version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: beer-database
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    container_name: db
    ports:
      - "3333:3333"
  app:
    build:
      context: .
    container_name: app
    volumes:
        - .:/go/beer-test
    working_dir: /go/beer-test
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db